development:
  adapter: postgresql
  database: UserProblems_development
  encoding: unicode
  pool: 5
  username: j_herrmann
  password: spastenfahne123

test:
  adapter: postgresql
  database: UserProblems_test
  encoding: unicode
  pool: 5
  username: j_herrmann
  password: spastenfahne123

production:
  adapter: postgresql
  database: UserProblems_production
  encoding: unicode
  pool: 5
  username: j_herrmann
  password: spastenfahne123
